version: "3.7"
services:

    ## --------------------------- ORION --------------------------- ##

    minio:
        image: gestaopv:latest

        networks:
            - fling ## Nome da rede interna

        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.role == manager
            labels:
                - traefik.enable=true
                - traefik.http.routers.gestaopv.rule=Host(`gestao.palavravivachurch.org`)
                - traefik.http.routers.gestaopv.entrypoints=websecure
                - traefik.http.routers.gestaopv.tls.certresolver=letsencryptresolver
                - traefik.http.services.gestaopv.loadbalancer.server.port=3000
                - traefik.http.services.gestaopv.loadbalancer.passHostHeader=true
                - traefik.http.routers.gestaopv.service=gestaopv

## --------------------------- ORION --------------------------- ##

networks:
    fling: ## Nome da rede interna
        external: true
        name: fling ## Nome da rede interna
